# Generated by Django 4.2 on 2024-06-30 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_paymentcaselists_paymenthistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentcaselists',
            name='payment_case_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
