# Generated by Django 4.2 on 2024-06-30 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_paymentcaselists_payment_case_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenthistory',
            name='payment_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
