# Generated by Django 4.2 on 2024-08-10 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_alter_paymenthistory_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenthistory',
            name='payment_date',
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
