# Generated by Django 4.2 on 2024-09-17 00:15

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_paymentcaselists_instraction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentcaselists',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
