# Generated by Django 4.2 on 2024-12-13 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0011_alter_paymentcasecartlist_payment_case'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentcasecartlist',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
