# Generated by Django 4.2 on 2024-12-13 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0012_paymentcasecartlist_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentcasecartlist',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
    ]
