# Generated by Django 4.2 on 2024-12-17 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_alter_membersupdateinformation_member_id'),
        ('payments', '0013_paymentcasecartlist_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='payment_id',
        ),
        migrations.AddField(
            model_name='paymentcasecartlist',
            name='membersID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='members.membersupdateinformation'),
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='PaymentCaseCart',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.paymentcasecartlist'),
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='billing_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.billinginformation'),
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
