# Generated by Django 4.2 on 2024-12-18 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0015_cartpaymentcase_alter_paymentcasecartlist_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartpaymentcase',
            name='payment_cases',
        ),
        migrations.AddField(
            model_name='cartpaymentcase',
            name='payment_cases',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.paymentcaselists'),
        ),
    ]
