# Generated by Django 4.2 on 2024-12-18 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0016_remove_cartpaymentcase_payment_cases_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartpaymentcase',
            name='membersID',
        ),
    ]
