# Generated by Django 4.2 on 2024-12-18 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_alter_membersupdateinformation_member_id'),
        ('payments', '0017_remove_cartpaymentcase_membersid'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartpaymentcase',
            name='membersID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='members.membersupdateinformation'),
        ),
    ]
