# Generated by Django 4.2 on 2024-12-19 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0018_cartpaymentcase_membersid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='billing_info',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='paymentcase',
            name='category',
        ),
        migrations.RemoveField(
            model_name='paymentcasecartlist',
            name='membersID',
        ),
        migrations.RemoveField(
            model_name='paymentcasecartlist',
            name='payment_case',
        ),
        migrations.RemoveField(
            model_name='paymentcasecartlist',
            name='user',
        ),
        migrations.RemoveField(
            model_name='paymenthistory',
            name='PaymentCaseCart',
        ),
        migrations.RemoveField(
            model_name='paymenthistory',
            name='billing_info',
        ),
        migrations.RemoveField(
            model_name='paymenthistory',
            name='payment_case',
        ),
        migrations.RemoveField(
            model_name='paymenthistory',
            name='user',
        ),
        migrations.DeleteModel(
            name='BillingInformation',
        ),
        migrations.DeleteModel(
            name='Categories',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='PaymentCase',
        ),
        migrations.DeleteModel(
            name='PaymentCaseCartList',
        ),
        migrations.DeleteModel(
            name='PaymentHistory',
        ),
    ]
