# Generated by Django 4.2 on 2025-01-01 19:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('members', '0007_alter_membersupdateinformation_member_id'),
        ('payments', '0019_remove_payment_billing_info_remove_payment_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentCaseCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(unique=True)),
                ('membersID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.membersupdateinformation')),
                ('payment_cases', models.ManyToManyField(blank=True, to='payments.paymentcaselists')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
