# Generated by Django 4.2 on 2025-01-02 07:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('members', '0007_alter_membersupdateinformation_member_id'),
        ('payments', '0020_paymentcasecart'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('membersID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members_id', to='members.membersupdateinformation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentCases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('stripe_payment_link', models.URLField()),
                ('payment_case_link', models.CharField(blank=True, max_length=255, null=True)),
                ('qr_code_image', models.ImageField(blank=True, null=True, upload_to='payments/qrcodes/')),
                ('case_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], max_length=50)),
                ('category', models.CharField(choices=[('service', 'Service'), ('donation', 'Donation'), ('marriageSchoolRegFee', 'Marriage School Registration Fee'), ('abentChildrenRegFee', 'Absent Children Registration Fee'), ('abentYouthRegFee', 'Absent Youth Registration Fee'), ('churchProjectSupportFree', 'Church Project Support Fee')], default='service', max_length=100)),
                ('instructions', models.TextField(default='If you need guidance on how to make a payment, please contact the office for assistance.')),
                ('type', models.CharField(choices=[('onetime', 'One-Time'), ('recurring', 'Recurring')], max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='payments/case_images/')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('requires_delivery', models.BooleanField(default=False)),
                ('slug', models.SlugField(unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CartPaymentCases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('slug', models.SlugField(unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='payments.cartpayment')),
                ('payment_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_cases', to='payments.paymentcases')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_cases', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
