# Generated by Django 4.2 on 2025-01-02 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0022_category_alter_cartpaymentcases_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentcases',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.category'),
        ),
    ]
