# Generated by Django 4.2 on 2025-01-04 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0023_alter_paymentcases_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderpaymentcase',
            name='cart_payment',
        ),
        migrations.RemoveField(
            model_name='orderpaymentcase',
            name='user',
        ),
        migrations.RemoveField(
            model_name='paymentcasecart',
            name='membersID',
        ),
        migrations.RemoveField(
            model_name='paymentcasecart',
            name='payment_cases',
        ),
        migrations.RemoveField(
            model_name='paymentcasecart',
            name='user',
        ),
        migrations.RemoveField(
            model_name='paymentcaselists',
            name='created_by',
        ),
        migrations.AlterField(
            model_name='paymentcases',
            name='stripe_payment_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='CartPaymentCase',
        ),
        migrations.DeleteModel(
            name='OrderPaymentCase',
        ),
        migrations.DeleteModel(
            name='PaymentCaseCart',
        ),
        migrations.DeleteModel(
            name='PaymentCaseLists',
        ),
    ]
