# Generated by Django 4.2 on 2024-05-28 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail_title', models.CharField(blank=True, max_length=200, null=True)),
                ('short_review', models.TextField(blank=True, max_length=1000, null=True)),
                ('video_url', models.URLField(blank=True, null=True)),
                ('number_of_participants', models.PositiveIntegerField(default=100)),
                ('held_date', models.DateField()),
                ('thumbnail_image', models.ImageField(blank=True, null=True, upload_to='event_gallery/thumbnails/%Y/%m/%d')),
                ('viewers_count', models.PositiveIntegerField(default=0)),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('post_events', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.event')),
            ],
            options={
                'ordering': ['-held_date', '-created'],
            },
        ),
        migrations.CreateModel(
            name='PostEventImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='event_gallery/images/%Y/%m/%d')),
                ('event_gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='events.eventgallery')),
            ],
        ),
    ]
