# Generated by Django 4.2 on 2024-09-09 23:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0004_event_status_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsAndAnnouncements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='newsAnnouncement_images/')),
                ('link', models.URLField(blank=True, null=True)),
                ('announce_to', models.TextField(blank=True, max_length=100, null=True)),
                ('announcer', models.CharField(blank=True, max_length=100, null=True)),
                ('category', models.CharField(choices=[('news', 'News'), ('announcement', 'Announcement')], default='news', max_length=20)),
                ('emergence_type', models.CharField(choices=[('urgent', 'Urgent'), ('on_time', 'On-Time'), ('as_quick_as', 'As Quick As')], default='on_time', max_length=20)),
                ('reference_source', models.CharField(blank=True, max_length=100, null=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_announcements', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
