# Generated by Django 4.2 on 2025-01-19 07:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0005_newsandannouncements'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemindMeUpcomingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('massage', models.TextField(default='Upcoming Event Tomorrow:This is a polite reminder that the scheduled event will take place tomorrow. Please ensure you are prepared & ready to participate.')),
                ('is_passed', models.BooleanField(default=False)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event', to='events.event')),
                ('your_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remainder', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
