# Generated by Django 4.2 on 2024-06-04 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='archivelink',
            old_name='url',
            new_name='url_link',
        ),
    ]
