# Generated by Django 4.2 on 2024-06-04 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia', '0002_rename_url_archivelink_url_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivelink',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='multimedia/ArchiveLink/'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='video_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='archivelink',
            name='description',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='archivelink',
            name='url_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='multimedia/gallery/'),
        ),
        migrations.AlterField(
            model_name='usermanual',
            name='published_by',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usermanual',
            name='version',
            field=models.CharField(default=1, max_length=20),
        ),
    ]
