# Generated by Django 4.2 on 2024-06-04 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia', '0003_archivelink_file_gallery_video_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivelink',
            name='external_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
