# Generated by Django 4.2 on 2024-06-04 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia', '0004_archivelink_external_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookslibrary',
            name='visibility',
            field=models.CharField(choices=[('public', 'public'), ('private', 'private')], default='private', max_length=50),
        ),
    ]
