# Generated by Django 4.2 on 2024-06-04 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia', '0005_bookslibrary_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookslibrary',
            name='activeForVote',
            field=models.BooleanField(default=False),
        ),
    ]
