# Generated by Django 4.2 on 2024-06-06 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia', '0006_bookslibrary_activeforvote'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookslibrary',
            name='voteCount',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
