# Generated by Django 4.2 on 2024-06-09 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia', '0008_bookslibrary_voters_alter_bookslibrary_votecount'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookslibrary',
            name='published_by',
            field=models.DateField(blank=True, max_length=100, null=True),
        ),
    ]
