# Generated by Django 4.2 on 2024-06-09 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia', '0009_bookslibrary_published_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookslibrary',
            name='published_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
