# Generated by Django 4.2 on 2024-06-10 04:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('multimedia', '0010_alter_bookslibrary_published_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookslibrary',
            options={'ordering': ['-published_date', '-created_at']},
        ),
        migrations.CreateModel(
            name='SpiritualPoemSong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(blank=True, max_length=200, null=True)),
                ('type', models.CharField(choices=[('poem', 'Poem'), ('song', 'Song')], max_length=4)),
                ('discretion', models.TextField(blank=True, max_length=200, null=True)),
                ('language', models.CharField(choices=[('en', 'English'), ('am', 'Amharic'), ('other', 'Other')], default='en', max_length=5)),
                ('published_date', models.DateField(blank=True, null=True)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='multimedia/spiritual_poems_songs/audio/')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='multimedia/spiritual_poems_songs/covers/')),
                ('link', models.URLField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-published_date', '-created_at'],
            },
        ),
    ]
