# Generated by Django 4.2 on 2024-06-10 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia', '0011_alter_bookslibrary_options_spiritualpoemsong'),
    ]

    operations = [
        migrations.AddField(
            model_name='spiritualpoemsong',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='multimedia/spiritual_poems_songs/pdf/'),
        ),
    ]
