# Generated by Django 4.2 on 2025-01-21 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia', '0014_praiseglory_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermanual',
            name='published_by',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
