# Generated by Django 4.2 on 2024-04-02 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_comment_slug_sermon_slug_alter_sermon_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sermon',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
