# Generated by Django 4.2 on 2024-05-15 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_baptizedcertification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='baptizedcertification',
            old_name='school_type',
            new_name='baptize_type',
        ),
    ]
