# Generated by Django 4.2 on 2024-05-22 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_membersupdateinformation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membersupdateinformation',
            name='user',
        ),
        migrations.RemoveField(
            model_name='relative',
            name='member',
        ),
        migrations.DeleteModel(
            name='Child',
        ),
        migrations.DeleteModel(
            name='MembersUpdateInformation',
        ),
        migrations.DeleteModel(
            name='Relative',
        ),
    ]
