# Generated by Django 4.2 on 2024-09-07 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_remove_membersupdateinformation_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FatherOfRepentanceLists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='fathers_of_repentance/')),
                ('location', models.CharField(max_length=255)),
                ('availability_days', models.CharField(help_text='e.g. Monday to Friday', max_length=255)),
                ('availability_hours', models.CharField(help_text='e.g. 9:00 AM to 5:00 PM', max_length=255)),
                ('church_serving', models.CharField(help_text='Full-time serving church', max_length=255)),
                ('experience_summary', models.TextField()),
                ('communication_preference', models.CharField(choices=[('email', 'Email'), ('phone', 'Phone'), ('other', 'Other')], default='phone', max_length=10)),
                ('communication_information', models.CharField(help_text='Might be active phone, email, whatsappNumber, telegramNumber', max_length=255)),
                ('availability_states', models.CharField(choices=[('active', 'active'), ('deactivated', 'deactivated')], default='active', max_length=20)),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='GroupMassageToSonOfRepentance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(help_text='Message to Sons of Repentance')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True)),
                ('father_of_repentance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.fatherofrepentancelists')),
            ],
        ),
    ]
