# Generated by Django 4.2 on 2024-09-08 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0011_fatherofrepentancelists_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fatherofrepentancelists',
            name='title_serving',
            field=models.CharField(blank=True, help_text='title position of serving in church', max_length=255, null=True),
        ),
    ]
