# Generated by Django 4.2 on 2024-09-09 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0012_fatherofrepentancelists_title_serving'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fatherofrepentancelists',
            name='image',
            field=models.ImageField(help_text='Recommended size: 800px (width) by 450px (height).', upload_to='fathers_of_repentance/'),
        ),
    ]
