# Generated by Django 4.2 on 2024-06-12 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blog_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='web_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
