# Generated by Django 4.2 on 2024-06-19 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marriage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signupformeetevents',
            name='confirmation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
