# Generated by Django 4.2 on 2024-06-19 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marriage', '0002_alter_signupformeetevents_confirmation'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetevents',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meetevents',
            name='status',
            field=models.CharField(default='active', max_length=50),
        ),
        migrations.AlterField(
            model_name='signupformeetevents',
            name='confirmation',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
