# Generated by Django 4.2 on 2024-08-18 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marriage', '0003_meetevents_end_time_alter_meetevents_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resources',
            name='category',
            field=models.CharField(choices=[('PreMarital', 'PreMarital'), ('PostMarital', 'PostMarital')], default='PreMarital', max_length=50),
        ),
    ]
