# Generated by Django 4.2 on 2024-08-19 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marriage', '0004_resources_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
