# Generated by Django 4.2 on 2024-08-26 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marriage', '0008_alter_results_score_subtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='signupformeetevents',
            name='attended_confirmation_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='signupformeetevents',
            name='is_attended',
            field=models.BooleanField(default=False),
        ),
    ]
