# Generated by Django 4.2 on 2024-04-04 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='static/audio'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
