# Generated by Django 4.2 on 2024-04-13 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0007_result_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='course_image/%Y/%m/%d'),
        ),
    ]
