# Generated by Django 4.2 on 2024-04-14 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0010_quationsandanswer_is_answered'),
    ]

    operations = [
        migrations.AddField(
            model_name='quationsandanswer',
            name='viewed_by',
            field=models.CharField(choices=[('public', 'public'), ('private', 'private')], default='private', max_length=100),
        ),
    ]
