# Generated by Django 4.2 on 2024-04-17 00:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schools', '0011_quationsandanswer_viewed_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('satisfaction_rating', models.IntegerField(default=0, help_text='Satisfaction rating from 0 to 5')),
                ('readers_count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='FAQReader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_satisfied', models.BooleanField(default=False)),
                ('faq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.faq')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'faq')},
            },
        ),
    ]
