# Generated by Django 4.2 on 2024-04-19 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0013_faq_created_faq_slug_faq_updated_faqreader_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='faqreader',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
