# Generated by Django 4.2 on 2024-04-19 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0014_alter_faq_slug_alter_faqreader_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faq',
            name='satisfaction_rating',
        ),
        migrations.AddField(
            model_name='faqreader',
            name='satisfaction_rating',
            field=models.IntegerField(default=0, help_text='Satisfaction rating from 0 to 5'),
        ),
        migrations.AlterField(
            model_name='faqreader',
            name='is_satisfied',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], max_length=50),
        ),
    ]
