# Generated by Django 4.2 on 2024-04-21 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0016_alter_faqreader_is_satisfied'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faqreader',
            name='is_satisfied',
        ),
        migrations.AddField(
            model_name='faq',
            name='is_satisfied',
            field=models.BooleanField(default=False),
        ),
    ]
