# Generated by Django 4.2 on 2024-04-21 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0018_relatedresource'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RelatedResource',
            new_name='FaqRelatedResource',
        ),
    ]
