# Generated by Django 4.2 on 2024-04-21 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0019_rename_relatedresource_faqrelatedresource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='school_type',
            field=models.CharField(choices=[('sundaySchoolYouth ', 'youthSchool'), ('sundaySchoolchildren ', 'childrenSchool')], max_length=100),
        ),
    ]
