# Generated by Django 4.2 on 2024-04-21 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0020_alter_course_school_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='school_type',
            field=models.CharField(choices=[('sundaySchoolYouth', 'youthSchool'), ('sundaySchoolChildren', 'childrenSchool')], max_length=100),
        ),
    ]
