# Generated by Django 4.2 on 2024-05-22 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membersupdateinformation',
            name='marital_status',
            field=models.CharField(choices=[('married', 'married'), ('single', 'single')], max_length=100),
        ),
    ]
