# Generated by Django 4.2 on 2024-05-22 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_alter_membersupdateinformation_marital_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='age',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='child',
            name='gender',
            field=models.CharField(choices=[('M', 'M'), ('F', 'F')], default='male-or-female', max_length=20),
        ),
        migrations.AddField(
            model_name='membersupdateinformation',
            name='how_mony_children',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='membersupdateinformation',
            name='how_mony_relatives',
            field=models.SmallIntegerField(default=0),
        ),
    ]
