# Generated by Django 4.2 on 2024-05-24 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_child_age_child_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membersupdateinformation',
            name='member_id',
            field=models.CharField(default='ID', editable=False, max_length=100, unique=True),
        ),
    ]
