# Generated by Django 4.2 on 2024-05-24 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_membersupdateinformation_member_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='age',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='child',
            name='gender',
            field=models.CharField(choices=[('M', 'M'), ('F', 'F')], max_length=20),
        ),
        migrations.AlterField(
            model_name='membersupdateinformation',
            name='member_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
