# Generated by Django 4.2 on 2024-05-26 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_alter_child_age_alter_child_gender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membersupdateinformation',
            name='how_mony_children',
        ),
        migrations.RemoveField(
            model_name='membersupdateinformation',
            name='how_mony_relatives',
        ),
        migrations.AddField(
            model_name='membersupdateinformation',
            name='member_status',
            field=models.CharField(choices=[('active', 'active'), ('pending', 'pending')], default='pending', max_length=100),
        ),
        migrations.AlterField(
            model_name='membersupdateinformation',
            name='member_id',
            field=models.CharField(default='m', editable=False, max_length=10, unique=True),
        ),
    ]
