# Generated by Django 4.2 on 2024-05-27 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_remove_membersupdateinformation_how_mony_children_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membersupdateinformation',
            name='member_id',
            field=models.CharField(editable=False, max_length=10, unique=True),
        ),
    ]
