# Generated by Django 4.2 on 2024-09-02 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopProducts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopproduct',
            name='category',
            field=models.CharField(choices=[('photoFrames', 'photoFrames'), ('outSourcesProducts ', 'outSourcesProducts'), ('inOurStore', 'inOurStore')], default='inOurStore', max_length=50),
        ),
        migrations.AddField(
            model_name='shopproduct',
            name='specification',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
